services:

  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  Netlogix\Nxgooglelocations\Service\:
    autowire: true
    public: true
    resource: '../Classes/Service/*'

  Netlogix\Nxgooglelocations\Domain\Repository\:
    autowire: true
    public: true
    resource: '../Classes/Domain/Repository/*'

  Netlogix\Nxgooglelocations\Command\BatchCommand:
    autowire: true
    tags:
      - name: 'console.command'
        command: 'nxgooglelocations:runscheduledjobs'
