services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Netlogix\Nxgooglelocations\:
    resource: '../Classes/*'

  Netlogix\Nxgooglelocations\Service\:
    public: true
    resource: '../Classes/Service/*'

  Netlogix\Nxgooglelocations\Domain\Repository\:
    public: true
    resource: '../Classes/Domain/Repository/*'
